{% set name = "visvis" %}
{% set version = "1.11.3" %}
{% set sha256 = "b2bfb4142b214e50db62e0813c05de8e16c5a4c29e37e101476a56b8750c9533" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - pyopengl

test:
  imports:
    - visvis
    - visvis.processing

about:
  home: https://github.com/almarklein/visvis
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis
  summary: Visvis - the object oriented approach to visualization
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - almarklein
