{% set version = "1.9.4" %}

package:
  name: visvis
  version: {{ version }}

source:
  fn: visvis-{{ version }}.zip
  url: https://pypi.python.org/packages/83/63/68eb3eb906cf94c78079136d96bff1c9515ec998a73c61f364b1fd97b3c2/visvis-{{ version }}.zip
  md5: 004b91ddf34c0cdb035eb0dc66421578

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - pyopengl

test:
  imports:
    - visvis

about:
  home: https://github.com/almarklein/visvis
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis
  summary: The object oriented approach to visualization
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - almarklein
