{% set name = "visvis" %}
{% set version = "1.12.2" %}
{% set sha256 = "ccfc5fc81223080f1d344617816d8a1acae462a80fb753e54ae2cdcb0af14705" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - pyopengl

test:
  imports:
    - visvis
    - visvis.processing

about:
  home: https://github.com/almarklein/visvis
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis
  summary: Visvis - the object oriented approach to visualization
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - almarklein
